name: Build libhkl library

on: push

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:
    name: build job
    runs-on: ubuntu-20.04

    steps:

    - name: Diagnostics
      run: |
        apt update
        apt-cache show gobject-introspection  # | grep Version
        apt-cache show libgsl-dev  # | grep Version
        cat /etc/os-release
        which git
        which make
        which autoconf
